name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-
      - uses: jetli/wasm-pack-action@v0.4.0
        name: Install wasm-pack
        with:
          version: 'latest'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build JS lib
        run: |
          npm install
          npm run prepare-package
      - name: Run node JS example
        run: |
          cd examples/node
          npm install
          npm start
      - name: Build frontend JS example
        run: |
          cd examples/frontend
          npm install
          npm run build